Repository boradesanket13/Blaze, pull requests merged in 2022-12, with the labels that each got.

#105 modifies ui
  index.html
  script.js
  style.css
Labels: Intermediate, points:10, codepeak 22

#112 feat: add prettier and editorconfig.
  .editorconfig
  .prettierrc
Labels: points:5, codepeak 22

#106 Fixed the error in flags
  script.js
Labels: points:10, codepeak 22
